# Generated by Django 2.2.6 on 2021-03-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
